# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{alexa}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wojciech Wnętrzak"]
  s.date = %q{2010-01-28}
  s.description = %q{Alexa Web Information Service library (AWIS)}
  s.email = %q{w.wnetrzak@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "alexa.gemspec",
     "lib/alexa.rb",
     "lib/alexa/config.rb",
     "lib/alexa/url_info.rb",
     "test/config_test.rb",
     "test/fixtures/empty.xml",
     "test/fixtures/polsl.xml",
     "test/fixtures/polsl_small.xml",
     "test/test_helper.rb",
     "test/url_info_test.rb"
  ]
  s.homepage = %q{http://github.com/morgoth/alexa}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Alexa Web Information Service library}
  s.test_files = [
    "test/url_info_test.rb",
     "test/config_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
    else
      s.add_dependency(%q<xml-simple>, [">= 0"])
    end
  else
    s.add_dependency(%q<xml-simple>, [">= 0"])
  end
end

